// REDUX ACTION TYPES
export const SET_QUOTE = 'SET_QUOTE';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const HOMEPRODUCTFILTER = 'HOMEPRODUCTFILTER';
export const ADDTOCARDDATA = 'ADDTOCARDDATA';